# Generated by Django 4.0 on 2021-12-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='sfed',
            fields=[
                ('BusName', models.CharField(max_length=100)),
                ('Bus_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Sce', models.JSONField(blank=True, default=dict)),
                ('curr_s', models.CharField(default='NOT AVAILABLE', max_length=100)),
                ('days', models.CharField(default='SU MO TU WE TH FR SA', max_length=100)),
            ],
        ),
    ]
