# Generated by Django 4.0 on 2021-12-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SFE', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='links',
        ),
    ]
